export const DEFAULT_PREFERENCES = {
    theme: 'one-dark',
    fontSize: 16,
    lineHeight: 1.6,
    codeFontSize: 14,
    editorLineWidth: '100%',
    autoSave: true,
    autoSaveDelay: 5000,
    typewriter: false,
    focus: false,
    sourceCode: false,
    preferLooseListItem: true,
    bulletListMarker: '-',
    orderListDelimiter: '.',
    tabSize: 4,
    listIndentation: 1,
    autoPairBracket: true,
    autoPairMarkdownSyntax: true,
    autoPairQuote: true,
    hideQuickInsertHint: false,
    hideLinkPopup: false,
    codeBlockLineNumbers: false,
    trimUnnecessaryCodeBlockEmptyLines: true,
    sequenceTheme: 'hand',
    showTabBar: true,
    textDirection: 'ltr',
    hideToolbar: false
};
