/**
 * Capability Registry
 *
 * Central registry for agent capabilities. Any agent can discover and invoke
 * any registered capability via delegation tools generated by this module.
 */

import { tool, type ToolSet } from 'ai'
import { z } from 'zod'
import type { Capability, CapabilityContext, DelegationLog } from './types'

// Module-level state
const capabilities = new Map<string, Capability>()
const delegationLogs: DelegationLog[] = []
const MAX_DELEGATION_LOGS = 200

// ============================================================================
// Registry API
// ============================================================================

export function registerCapability(cap: Capability): void {
  capabilities.set(cap.name, cap)
}

export function getCapability(name: string): Capability | undefined {
  return capabilities.get(name)
}

export function listCapabilities(): Array<{ name: string; description: string }> {
  return Array.from(capabilities.values()).map((c) => ({
    name: c.name,
    description: c.description,
  }))
}

// ============================================================================
// Delegation Tool Generation
// ============================================================================

/**
 * Generate AI SDK v6 tools that delegate to registered capabilities.
 * Each tool emits custom-progress events for visibility in ActivityStream.
 */
export function generateDelegationTools(
  agentName: string,
  capabilityNames: string[],
  context: CapabilityContext
): ToolSet {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tools: Record<string, any> = {}

  for (const capName of capabilityNames) {
    const cap = capabilities.get(capName)
    if (!cap) continue

    // Convert dotted name to snake_case tool name (e.g., "notes.search" → "delegate_notes_search")
    const toolName = `delegate_${capName.replace(/\./g, '_')}`

    tools[toolName] = tool({
      description: cap.description,
      inputSchema: cap.inputSchema as z.ZodType<any, any, any>,
      execute: async (input: any) => {
        const startMs = Date.now()

        // Emit progress start
        context.emitEvent?.({
          type: 'custom-progress',
          data: { step: `[${capName}] Starting...`, delegation: true },
        })

        try {
          const result = await cap.execute(input, context)
          const durationMs = Date.now() - startMs

          // Emit progress complete
          context.emitEvent?.({
            type: 'custom-progress',
            data: {
              step: `[${capName}] Done (${durationMs}ms)`,
              delegation: true,
              status: 'complete',
            },
          })

          logDelegation({
            parentAgent: agentName,
            capability: capName,
            inputSummary: JSON.stringify(input).slice(0, 200),
            outputSummary: result.slice(0, 200),
            durationMs,
            timestamp: new Date().toISOString(),
          })

          return result
        } catch (err) {
          const durationMs = Date.now() - startMs

          context.emitEvent?.({
            type: 'custom-progress',
            data: {
              step: `[${capName}] Failed: ${err instanceof Error ? err.message : String(err)}`,
              delegation: true,
              status: 'error',
            },
          })

          logDelegation({
            parentAgent: agentName,
            capability: capName,
            inputSummary: JSON.stringify(input).slice(0, 200),
            outputSummary: `ERROR: ${err instanceof Error ? err.message : String(err)}`,
            durationMs,
            timestamp: new Date().toISOString(),
          })

          return `Error executing ${capName}: ${err instanceof Error ? err.message : String(err)}`
        }
      },
    })
  }

  return tools
}

// ============================================================================
// Delegation Logging
// ============================================================================

function logDelegation(log: DelegationLog): void {
  delegationLogs.push(log)
  // Cap to prevent unbounded memory growth in long-running servers
  if (delegationLogs.length > MAX_DELEGATION_LOGS) {
    delegationLogs.splice(0, delegationLogs.length - MAX_DELEGATION_LOGS)
  }
  console.info(
    JSON.stringify({
      type: 'delegation',
      parentAgent: log.parentAgent,
      capability: log.capability,
      durationMs: log.durationMs,
      inputLength: log.inputSummary.length,
    })
  )
}

export function getDelegationLogs(): readonly DelegationLog[] {
  return delegationLogs
}

export function clearDelegationLogs(): void {
  delegationLogs.length = 0
}
